### ISSUE TITLE
AttributeError: module 'hashlib' has no attribute 'scrypt'

### ISSUE THREAD

**Issue by ghost** [gdavid7/cryptocode#2]
8:42 ~/www/trio_ircproxy-main $ python3 trio_ircproxy.py 
Traceback (most recent call last):
  File "trio_ircproxy.py", line 89, in <module>
    Auth_json['userlist']['user'] = text_encode('pass')
  File "trio_ircproxy.py", line 83, in text_encode
    text = cryptocode.encrypt(text, text)
  File "/home/Ashburry/.local/lib/python3.8/site-packages/cryptocode/myfunctions.py", line 15, in encrypt
    private_key = hashlib.scrypt(
AttributeError: module 'hashlib' has no attribute 'scrypt'

**Comment by ghost** [comment]
maybe passlib.hash.scrypt() ?

**Comment by gdavid7** [comment]
Hi, sorry for the late reply. If you are still having problems with this, would you mind letting me know what OS you are on?
You may need to have OpenSSL 1.1+ installed.

Thanks.

**Comment by ghost** [comment]
Sorry, I have not using this app any longer. I am now using "from scrypt
import hash as chash" which takes a salt so it is kind of slow. There is
another hash in there I may try using that has no salt and therefor maybe
faster. If not not I will give cryptocode another try.

Thank you.

**Comment by gdavid7** [comment]
Thank you for letting me know, good luck on your project.
