### ISSUE TITLE
Do you still maintain this project?

### ISSUE THREAD

**Issue by zareisajad** [gdavid7/cryptocode#3]
i found this package very useful and handy for one of my REAL projects, so i want to know if you maintain this or not, since the latest version's for 2020!

**Comment by s-dgershony** [comment]
Hi zareisajad, I have been busy with school and have not seen the need to make any improvements as of now. However, I would love to hear suggested changes and would implement them if needed! Glad to hear that this helped your project!

**Comment by gdavid7** [comment]
Hi zareisajad, I have been busy with school and have not seen the need to make any improvements as of now. However, I would love to hear suggested changes and would implement them if needed! Glad to hear that this helped your project!
